name: deploy

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
jobs:
  deploy:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.base.ref == 'master' &&
       (github.event.pull_request.author_association == 'OWNER' ||
        github.event.pull_request.author_association == 'COLLABORATOR'))
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: pip install touying

      - name: Make build dir
        run: mkdir build

      - name: Build the html
        run: |
          touying compile --root=src --output=build/main.html src/main.typ

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/main.html"

      # Deploy to GitHub Pages only on push events
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4


